# This makefile was created by hacking on the makefile.unx file in the
# wxWidgets/samples/richtext directory. Basically this reflects the general
# idea that one way of building Tarrasch on any platform is to first get
# the wxWidgets richtext sample working, then add in the Tarrasch files
# Note that I ignored the instruction below not to make modifications - I
# am not sure what is supposed to overwrite my changes!
#  Bill Forster 22Dec2015
#

# =========================================================================
#     This makefile was generated by
#     Bakefile 0.2.9 (http://www.bakefile.org)
#     Do not modify, all changes will be overwritten!
# =========================================================================

# -------------------------------------------------------------------------
# These are configurable options:
# -------------------------------------------------------------------------

# C++ compiler 
CXX = `$(WX_CONFIG) --cxx`

# Standard flags for C++ 
CXXFLAGS ?= 

# Standard preprocessor flags (common for CC and CXX) 
CPPFLAGS ?= 

# Standard linker flags (Bill Forster - added -ldl else sqlite3.c caused problems)
LDFLAGS ?= -ldl 

# Location and arguments of wx-config script 
WX_CONFIG ?= wx-config

# Port of the wx library to build against [gtk1,gtk2,msw,x11,motif,osx_cocoa,osx_carbon,dfb]
WX_PORT ?= $(shell $(WX_CONFIG) --query-toolkit)

# Use DLL build of wx library to use? [0,1]
WX_SHARED ?= $(shell if test -z `$(WX_CONFIG) --query-linkage`; then echo 1; else echo 0; fi)

# Compile Unicode build of wxWidgets? [0,1]
WX_UNICODE ?= $(shell $(WX_CONFIG) --query-chartype | sed 's/unicode/1/;s/ansi/0/')

# Version of the wx library to build against. 
WX_VERSION ?= $(shell $(WX_CONFIG) --query-version | sed -e 's/\([0-9]*\)\.\([0-9]*\)/\1\2/')



# -------------------------------------------------------------------------
# Do not modify the rest of this file!
# -------------------------------------------------------------------------

### Variables: ###

CPPDEPS = -MT$@ -MF`echo $@ | sed -e 's,\.o$$,.d,'` -MD -MP
WX_VERSION_MAJOR = $(shell echo $(WX_VERSION) | cut -c1,1)
WX_VERSION_MINOR = $(shell echo $(WX_VERSION) | cut -c2,2)
WX_CONFIG_FLAGS = $(WX_CONFIG_UNICODE_FLAG) $(WX_CONFIG_SHARED_FLAG) \
	--toolkit=$(WX_PORT) --version=$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)
TARRASCH_CXXFLAGS = -I. `$(WX_CONFIG) --cxxflags $(WX_CONFIG_FLAGS)` $(CPPFLAGS) \
	$(CXXFLAGS)
TARRASCH_OBJECTS =  \
	./obj/Atom.o \
	./obj/BoardBitmap40.o \
	./obj/BoardBitmap54.o \
	./obj/BoardSetupControl.o \
	./obj/BoardSetup.o \
	./obj/Book.o \
	./obj/BookDialog.o \
	./obj/Canvas.o \
	./obj/CentralWorkSaver.o \
	./obj/ClipboardDialog.o \
	./obj/ClockDialog.o \
	./obj/CompactGame.o \
	./obj/CompressMoves.o \
	./obj/CreateDatabaseDialog.o \
	./obj/CtrlBox2.o \
	./obj/CtrlBoxBookMoves.o \
	./obj/CtrlBox.o \
	./obj/CtrlChessTxt.o \
	./obj/Database.o \
	./obj/DbDialog.o \
	./obj/DbMaintenance.o \
	./obj/DbPrimitives.o \
	./obj/EngineDialog.o \
	./obj/GameClock.o \
	./obj/GameClockHalf.o \
	./obj/GameDetailsDialog.o \
	./obj/GameDocument.o \
	./obj/GameLifecycle.o \
	./obj/GameLogic.o \
	./obj/GamePrefixDialog.o \
	./obj/GamesCache.o \
	./obj/GamesDialog.o \
	./obj/GameView.o \
	./obj/GeneralDialog.o \
	./obj/GraphicBoard.o \
	./obj/Lang.o \
	./obj/Log.o \
	./obj/LogDialog.o \
	./obj/MacRybka.o \
	./obj/main.o \
	./obj/MaintenanceDialog.o \
	./obj/MiniBoard.o \
	./obj/MoveTree.o \
	./obj/PackedGame.o \
	./obj/PgnDialog.o \
	./obj/PgnFiles.o \
	./obj/PgnRead.o \
	./obj/PlayerDialog.o \
	./obj/PopupControl.o \
	./obj/PositionDialog.o \
	./obj/Repository.o \
	./obj/Session.o \
	./obj/Tabs.o \
	./obj/thc.o \
	./obj/TrainingDialog.o \
	./obj/sqlite3.o \
	./obj/Undo.o


### Conditionally set variables: ###

ifeq ($(WX_UNICODE),0)
WX_CONFIG_UNICODE_FLAG = --unicode=no
endif
ifeq ($(WX_UNICODE),1)
WX_CONFIG_UNICODE_FLAG = --unicode=yes
endif
ifeq ($(WX_SHARED),0)
WX_CONFIG_SHARED_FLAG = --static=yes
endif
ifeq ($(WX_SHARED),1)
WX_CONFIG_SHARED_FLAG = --static=no
endif


### Targets: ###

all: test_for_selected_wxbuild tarrasch

install: 

uninstall: 

clean: 
	rm -f ./obj/.o
	rm -f ./obj/.d
	rm -f richtext

test_for_selected_wxbuild: 
	@$(WX_CONFIG) $(WX_CONFIG_FLAGS)

tarrasch: $(TARRASCH_OBJECTS)
	$(CXX) -o $@ $(TARRASCH_OBJECTS) $(LDFLAGS) `$(WX_CONFIG) $(WX_CONFIG_FLAGS) --libs richtext,adv,html,core,xml,base`

richtext_richtext.o: ./richtext.cpp
	$(CXX) -c -o $@ $(TARRASCH_CXXFLAGS) $(CPPDEPS) $<

./obj/%.o: ./src/t3/%.cpp
	$(CXX) -c -o $@ $(TARRASCH_CXXFLAGS) -std=c++11 $(CPPDEPS) $<

./obj/%.o: ./src/t3/%.c
	gcc -c -o $@  $<
	
.PHONY: all install uninstall clean


# Dependencies tracking:
-include ./obj/*.d
