/****************************************************************************
 * Complement PrivateChessClasses.h by providing a shared instantation of
 *  the automatically generated lookup tables.
 *  Author:  Bill Forster
 *  License: MIT license. Full text of license is in associated file LICENSE
 *  Copyright 2010-2014, Bill Forster <billforsternz at gmail dot com>
 ****************************************************************************/
#include "PrivateChessDefs.h"
namespace thc
{

// All the lookup tables
#define P 1
#define B 2
#define N 4
#define R 8
#define Q 16
#define K 32

// GeneratedLookupTables.inc assumes a suitable type lte = lookup tables element
//  plus a bitmask convention for pieces using identifiers P,R,N,B,Q,K is 
//  defined
#include "GeneratedLookupTables.h"

// A lookup table to convert our character piece convention to the lookup
//  convention.
// Note for future reference. We could get a small performance boost, at the
//  cost of debuggability, by using this bitmask convention rather than our
//  ascii convention for pieces. The advantage would simply be that the
//  to_mask[] conversion would not then be required. In fact that used to be
//  how we did it, but we changed to the ascii convention which has many
//  advantages. Maybe a compromise where debug builds use the ascii convention
//  and release builds use a faster binary convention will be the ultimate
//  solution. We'll need a new api to convert to ascii convention for display
//  of board positions etc. if we do this.
lte to_mask[] =
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,   // 0x00-0x0f
     0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,   // 0x10-0x1f
     0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,   // 0x20-0x2f
     0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,   // 0x30-0x3f
     0,0,B,0,0,0,0,0,0,0,0,K,0,0,N,0,   // 0x40-0x4f    'B'=0x42, 'K'=0x4b, 'N'=0x4e
     P,Q,R,0,0,0,0,0,0,0,0,0,0,0,0,0,   // 0x50-0x5f    'P'=0x50, 'Q'=0x51, 'R'=0x52
     0,0,B,0,0,0,0,0,0,0,0,K,0,0,N,0,   // 0x60-0x6f    'b'=0x62, 'k'=0x6b, 'n'=0x6e
     P,Q,R,0,0,0,0,0,0,0,0,0,0,0,0,0};  // 0x70-0x7f    'p'=0x70, 'q'=0x71, 'r'=0x72
#undef P
#undef B
#undef N
#undef R
#undef Q
#undef K

// queen_lookup
const lte *queen_lookup[] =
{
    queen_lookup_a8,
    queen_lookup_b8,
    queen_lookup_c8,
    queen_lookup_d8,
    queen_lookup_e8,
    queen_lookup_f8,
    queen_lookup_g8,
    queen_lookup_h8,
    queen_lookup_a7,
    queen_lookup_b7,
    queen_lookup_c7,
    queen_lookup_d7,
    queen_lookup_e7,
    queen_lookup_f7,
    queen_lookup_g7,
    queen_lookup_h7,
    queen_lookup_a6,
    queen_lookup_b6,
    queen_lookup_c6,
    queen_lookup_d6,
    queen_lookup_e6,
    queen_lookup_f6,
    queen_lookup_g6,
    queen_lookup_h6,
    queen_lookup_a5,
    queen_lookup_b5,
    queen_lookup_c5,
    queen_lookup_d5,
    queen_lookup_e5,
    queen_lookup_f5,
    queen_lookup_g5,
    queen_lookup_h5,
    queen_lookup_a4,
    queen_lookup_b4,
    queen_lookup_c4,
    queen_lookup_d4,
    queen_lookup_e4,
    queen_lookup_f4,
    queen_lookup_g4,
    queen_lookup_h4,
    queen_lookup_a3,
    queen_lookup_b3,
    queen_lookup_c3,
    queen_lookup_d3,
    queen_lookup_e3,
    queen_lookup_f3,
    queen_lookup_g3,
    queen_lookup_h3,
    queen_lookup_a2,
    queen_lookup_b2,
    queen_lookup_c2,
    queen_lookup_d2,
    queen_lookup_e2,
    queen_lookup_f2,
    queen_lookup_g2,
    queen_lookup_h2,
    queen_lookup_a1,
    queen_lookup_b1,
    queen_lookup_c1,
    queen_lookup_d1,
    queen_lookup_e1,
    queen_lookup_f1,
    queen_lookup_g1,
    queen_lookup_h1
};


// rook_lookup
const lte *rook_lookup[] =
{
    rook_lookup_a8,
    rook_lookup_b8,
    rook_lookup_c8,
    rook_lookup_d8,
    rook_lookup_e8,
    rook_lookup_f8,
    rook_lookup_g8,
    rook_lookup_h8,
    rook_lookup_a7,
    rook_lookup_b7,
    rook_lookup_c7,
    rook_lookup_d7,
    rook_lookup_e7,
    rook_lookup_f7,
    rook_lookup_g7,
    rook_lookup_h7,
    rook_lookup_a6,
    rook_lookup_b6,
    rook_lookup_c6,
    rook_lookup_d6,
    rook_lookup_e6,
    rook_lookup_f6,
    rook_lookup_g6,
    rook_lookup_h6,
    rook_lookup_a5,
    rook_lookup_b5,
    rook_lookup_c5,
    rook_lookup_d5,
    rook_lookup_e5,
    rook_lookup_f5,
    rook_lookup_g5,
    rook_lookup_h5,
    rook_lookup_a4,
    rook_lookup_b4,
    rook_lookup_c4,
    rook_lookup_d4,
    rook_lookup_e4,
    rook_lookup_f4,
    rook_lookup_g4,
    rook_lookup_h4,
    rook_lookup_a3,
    rook_lookup_b3,
    rook_lookup_c3,
    rook_lookup_d3,
    rook_lookup_e3,
    rook_lookup_f3,
    rook_lookup_g3,
    rook_lookup_h3,
    rook_lookup_a2,
    rook_lookup_b2,
    rook_lookup_c2,
    rook_lookup_d2,
    rook_lookup_e2,
    rook_lookup_f2,
    rook_lookup_g2,
    rook_lookup_h2,
    rook_lookup_a1,
    rook_lookup_b1,
    rook_lookup_c1,
    rook_lookup_d1,
    rook_lookup_e1,
    rook_lookup_f1,
    rook_lookup_g1,
    rook_lookup_h1
};


// bishop_lookup
const lte *bishop_lookup[] =
{
    bishop_lookup_a8,
    bishop_lookup_b8,
    bishop_lookup_c8,
    bishop_lookup_d8,
    bishop_lookup_e8,
    bishop_lookup_f8,
    bishop_lookup_g8,
    bishop_lookup_h8,
    bishop_lookup_a7,
    bishop_lookup_b7,
    bishop_lookup_c7,
    bishop_lookup_d7,
    bishop_lookup_e7,
    bishop_lookup_f7,
    bishop_lookup_g7,
    bishop_lookup_h7,
    bishop_lookup_a6,
    bishop_lookup_b6,
    bishop_lookup_c6,
    bishop_lookup_d6,
    bishop_lookup_e6,
    bishop_lookup_f6,
    bishop_lookup_g6,
    bishop_lookup_h6,
    bishop_lookup_a5,
    bishop_lookup_b5,
    bishop_lookup_c5,
    bishop_lookup_d5,
    bishop_lookup_e5,
    bishop_lookup_f5,
    bishop_lookup_g5,
    bishop_lookup_h5,
    bishop_lookup_a4,
    bishop_lookup_b4,
    bishop_lookup_c4,
    bishop_lookup_d4,
    bishop_lookup_e4,
    bishop_lookup_f4,
    bishop_lookup_g4,
    bishop_lookup_h4,
    bishop_lookup_a3,
    bishop_lookup_b3,
    bishop_lookup_c3,
    bishop_lookup_d3,
    bishop_lookup_e3,
    bishop_lookup_f3,
    bishop_lookup_g3,
    bishop_lookup_h3,
    bishop_lookup_a2,
    bishop_lookup_b2,
    bishop_lookup_c2,
    bishop_lookup_d2,
    bishop_lookup_e2,
    bishop_lookup_f2,
    bishop_lookup_g2,
    bishop_lookup_h2,
    bishop_lookup_a1,
    bishop_lookup_b1,
    bishop_lookup_c1,
    bishop_lookup_d1,
    bishop_lookup_e1,
    bishop_lookup_f1,
    bishop_lookup_g1,
    bishop_lookup_h1
};


// knight_lookup
const lte *knight_lookup[] =
{
    knight_lookup_a8,
    knight_lookup_b8,
    knight_lookup_c8,
    knight_lookup_d8,
    knight_lookup_e8,
    knight_lookup_f8,
    knight_lookup_g8,
    knight_lookup_h8,
    knight_lookup_a7,
    knight_lookup_b7,
    knight_lookup_c7,
    knight_lookup_d7,
    knight_lookup_e7,
    knight_lookup_f7,
    knight_lookup_g7,
    knight_lookup_h7,
    knight_lookup_a6,
    knight_lookup_b6,
    knight_lookup_c6,
    knight_lookup_d6,
    knight_lookup_e6,
    knight_lookup_f6,
    knight_lookup_g6,
    knight_lookup_h6,
    knight_lookup_a5,
    knight_lookup_b5,
    knight_lookup_c5,
    knight_lookup_d5,
    knight_lookup_e5,
    knight_lookup_f5,
    knight_lookup_g5,
    knight_lookup_h5,
    knight_lookup_a4,
    knight_lookup_b4,
    knight_lookup_c4,
    knight_lookup_d4,
    knight_lookup_e4,
    knight_lookup_f4,
    knight_lookup_g4,
    knight_lookup_h4,
    knight_lookup_a3,
    knight_lookup_b3,
    knight_lookup_c3,
    knight_lookup_d3,
    knight_lookup_e3,
    knight_lookup_f3,
    knight_lookup_g3,
    knight_lookup_h3,
    knight_lookup_a2,
    knight_lookup_b2,
    knight_lookup_c2,
    knight_lookup_d2,
    knight_lookup_e2,
    knight_lookup_f2,
    knight_lookup_g2,
    knight_lookup_h2,
    knight_lookup_a1,
    knight_lookup_b1,
    knight_lookup_c1,
    knight_lookup_d1,
    knight_lookup_e1,
    knight_lookup_f1,
    knight_lookup_g1,
    knight_lookup_h1
};


// king_lookup
const lte *king_lookup[] =
{
    king_lookup_a8,
    king_lookup_b8,
    king_lookup_c8,
    king_lookup_d8,
    king_lookup_e8,
    king_lookup_f8,
    king_lookup_g8,
    king_lookup_h8,
    king_lookup_a7,
    king_lookup_b7,
    king_lookup_c7,
    king_lookup_d7,
    king_lookup_e7,
    king_lookup_f7,
    king_lookup_g7,
    king_lookup_h7,
    king_lookup_a6,
    king_lookup_b6,
    king_lookup_c6,
    king_lookup_d6,
    king_lookup_e6,
    king_lookup_f6,
    king_lookup_g6,
    king_lookup_h6,
    king_lookup_a5,
    king_lookup_b5,
    king_lookup_c5,
    king_lookup_d5,
    king_lookup_e5,
    king_lookup_f5,
    king_lookup_g5,
    king_lookup_h5,
    king_lookup_a4,
    king_lookup_b4,
    king_lookup_c4,
    king_lookup_d4,
    king_lookup_e4,
    king_lookup_f4,
    king_lookup_g4,
    king_lookup_h4,
    king_lookup_a3,
    king_lookup_b3,
    king_lookup_c3,
    king_lookup_d3,
    king_lookup_e3,
    king_lookup_f3,
    king_lookup_g3,
    king_lookup_h3,
    king_lookup_a2,
    king_lookup_b2,
    king_lookup_c2,
    king_lookup_d2,
    king_lookup_e2,
    king_lookup_f2,
    king_lookup_g2,
    king_lookup_h2,
    king_lookup_a1,
    king_lookup_b1,
    king_lookup_c1,
    king_lookup_d1,
    king_lookup_e1,
    king_lookup_f1,
    king_lookup_g1,
    king_lookup_h1
};


// pawn_white_lookup
const lte *pawn_white_lookup[] =
{
    pawn_white_lookup_a8,
    pawn_white_lookup_b8,
    pawn_white_lookup_c8,
    pawn_white_lookup_d8,
    pawn_white_lookup_e8,
    pawn_white_lookup_f8,
    pawn_white_lookup_g8,
    pawn_white_lookup_h8,
    pawn_white_lookup_a7,
    pawn_white_lookup_b7,
    pawn_white_lookup_c7,
    pawn_white_lookup_d7,
    pawn_white_lookup_e7,
    pawn_white_lookup_f7,
    pawn_white_lookup_g7,
    pawn_white_lookup_h7,
    pawn_white_lookup_a6,
    pawn_white_lookup_b6,
    pawn_white_lookup_c6,
    pawn_white_lookup_d6,
    pawn_white_lookup_e6,
    pawn_white_lookup_f6,
    pawn_white_lookup_g6,
    pawn_white_lookup_h6,
    pawn_white_lookup_a5,
    pawn_white_lookup_b5,
    pawn_white_lookup_c5,
    pawn_white_lookup_d5,
    pawn_white_lookup_e5,
    pawn_white_lookup_f5,
    pawn_white_lookup_g5,
    pawn_white_lookup_h5,
    pawn_white_lookup_a4,
    pawn_white_lookup_b4,
    pawn_white_lookup_c4,
    pawn_white_lookup_d4,
    pawn_white_lookup_e4,
    pawn_white_lookup_f4,
    pawn_white_lookup_g4,
    pawn_white_lookup_h4,
    pawn_white_lookup_a3,
    pawn_white_lookup_b3,
    pawn_white_lookup_c3,
    pawn_white_lookup_d3,
    pawn_white_lookup_e3,
    pawn_white_lookup_f3,
    pawn_white_lookup_g3,
    pawn_white_lookup_h3,
    pawn_white_lookup_a2,
    pawn_white_lookup_b2,
    pawn_white_lookup_c2,
    pawn_white_lookup_d2,
    pawn_white_lookup_e2,
    pawn_white_lookup_f2,
    pawn_white_lookup_g2,
    pawn_white_lookup_h2,
    pawn_white_lookup_a1,
    pawn_white_lookup_b1,
    pawn_white_lookup_c1,
    pawn_white_lookup_d1,
    pawn_white_lookup_e1,
    pawn_white_lookup_f1,
    pawn_white_lookup_g1,
    pawn_white_lookup_h1
};


// pawn_black_lookup
const lte *pawn_black_lookup[] =
{
    pawn_black_lookup_a8,
    pawn_black_lookup_b8,
    pawn_black_lookup_c8,
    pawn_black_lookup_d8,
    pawn_black_lookup_e8,
    pawn_black_lookup_f8,
    pawn_black_lookup_g8,
    pawn_black_lookup_h8,
    pawn_black_lookup_a7,
    pawn_black_lookup_b7,
    pawn_black_lookup_c7,
    pawn_black_lookup_d7,
    pawn_black_lookup_e7,
    pawn_black_lookup_f7,
    pawn_black_lookup_g7,
    pawn_black_lookup_h7,
    pawn_black_lookup_a6,
    pawn_black_lookup_b6,
    pawn_black_lookup_c6,
    pawn_black_lookup_d6,
    pawn_black_lookup_e6,
    pawn_black_lookup_f6,
    pawn_black_lookup_g6,
    pawn_black_lookup_h6,
    pawn_black_lookup_a5,
    pawn_black_lookup_b5,
    pawn_black_lookup_c5,
    pawn_black_lookup_d5,
    pawn_black_lookup_e5,
    pawn_black_lookup_f5,
    pawn_black_lookup_g5,
    pawn_black_lookup_h5,
    pawn_black_lookup_a4,
    pawn_black_lookup_b4,
    pawn_black_lookup_c4,
    pawn_black_lookup_d4,
    pawn_black_lookup_e4,
    pawn_black_lookup_f4,
    pawn_black_lookup_g4,
    pawn_black_lookup_h4,
    pawn_black_lookup_a3,
    pawn_black_lookup_b3,
    pawn_black_lookup_c3,
    pawn_black_lookup_d3,
    pawn_black_lookup_e3,
    pawn_black_lookup_f3,
    pawn_black_lookup_g3,
    pawn_black_lookup_h3,
    pawn_black_lookup_a2,
    pawn_black_lookup_b2,
    pawn_black_lookup_c2,
    pawn_black_lookup_d2,
    pawn_black_lookup_e2,
    pawn_black_lookup_f2,
    pawn_black_lookup_g2,
    pawn_black_lookup_h2,
    pawn_black_lookup_a1,
    pawn_black_lookup_b1,
    pawn_black_lookup_c1,
    pawn_black_lookup_d1,
    pawn_black_lookup_e1,
    pawn_black_lookup_f1,
    pawn_black_lookup_g1,
    pawn_black_lookup_h1
};


// good_king_position_lookup
const lte *good_king_position_lookup[] =
{
    good_king_position_lookup_a8,
    good_king_position_lookup_b8,
    good_king_position_lookup_c8,
    good_king_position_lookup_d8,
    good_king_position_lookup_e8,
    good_king_position_lookup_f8,
    good_king_position_lookup_g8,
    good_king_position_lookup_h8,
    good_king_position_lookup_a7,
    good_king_position_lookup_b7,
    good_king_position_lookup_c7,
    good_king_position_lookup_d7,
    good_king_position_lookup_e7,
    good_king_position_lookup_f7,
    good_king_position_lookup_g7,
    good_king_position_lookup_h7,
    good_king_position_lookup_a6,
    good_king_position_lookup_b6,
    good_king_position_lookup_c6,
    good_king_position_lookup_d6,
    good_king_position_lookup_e6,
    good_king_position_lookup_f6,
    good_king_position_lookup_g6,
    good_king_position_lookup_h6,
    good_king_position_lookup_a5,
    good_king_position_lookup_b5,
    good_king_position_lookup_c5,
    good_king_position_lookup_d5,
    good_king_position_lookup_e5,
    good_king_position_lookup_f5,
    good_king_position_lookup_g5,
    good_king_position_lookup_h5,
    good_king_position_lookup_a4,
    good_king_position_lookup_b4,
    good_king_position_lookup_c4,
    good_king_position_lookup_d4,
    good_king_position_lookup_e4,
    good_king_position_lookup_f4,
    good_king_position_lookup_g4,
    good_king_position_lookup_h4,
    good_king_position_lookup_a3,
    good_king_position_lookup_b3,
    good_king_position_lookup_c3,
    good_king_position_lookup_d3,
    good_king_position_lookup_e3,
    good_king_position_lookup_f3,
    good_king_position_lookup_g3,
    good_king_position_lookup_h3,
    good_king_position_lookup_a2,
    good_king_position_lookup_b2,
    good_king_position_lookup_c2,
    good_king_position_lookup_d2,
    good_king_position_lookup_e2,
    good_king_position_lookup_f2,
    good_king_position_lookup_g2,
    good_king_position_lookup_h2,
    good_king_position_lookup_a1,
    good_king_position_lookup_b1,
    good_king_position_lookup_c1,
    good_king_position_lookup_d1,
    good_king_position_lookup_e1,
    good_king_position_lookup_f1,
    good_king_position_lookup_g1,
    good_king_position_lookup_h1
};


// pawn_attacks_white_lookup
const lte *pawn_attacks_white_lookup[] =
{
    pawn_attacks_white_lookup_a8,
    pawn_attacks_white_lookup_b8,
    pawn_attacks_white_lookup_c8,
    pawn_attacks_white_lookup_d8,
    pawn_attacks_white_lookup_e8,
    pawn_attacks_white_lookup_f8,
    pawn_attacks_white_lookup_g8,
    pawn_attacks_white_lookup_h8,
    pawn_attacks_white_lookup_a7,
    pawn_attacks_white_lookup_b7,
    pawn_attacks_white_lookup_c7,
    pawn_attacks_white_lookup_d7,
    pawn_attacks_white_lookup_e7,
    pawn_attacks_white_lookup_f7,
    pawn_attacks_white_lookup_g7,
    pawn_attacks_white_lookup_h7,
    pawn_attacks_white_lookup_a6,
    pawn_attacks_white_lookup_b6,
    pawn_attacks_white_lookup_c6,
    pawn_attacks_white_lookup_d6,
    pawn_attacks_white_lookup_e6,
    pawn_attacks_white_lookup_f6,
    pawn_attacks_white_lookup_g6,
    pawn_attacks_white_lookup_h6,
    pawn_attacks_white_lookup_a5,
    pawn_attacks_white_lookup_b5,
    pawn_attacks_white_lookup_c5,
    pawn_attacks_white_lookup_d5,
    pawn_attacks_white_lookup_e5,
    pawn_attacks_white_lookup_f5,
    pawn_attacks_white_lookup_g5,
    pawn_attacks_white_lookup_h5,
    pawn_attacks_white_lookup_a4,
    pawn_attacks_white_lookup_b4,
    pawn_attacks_white_lookup_c4,
    pawn_attacks_white_lookup_d4,
    pawn_attacks_white_lookup_e4,
    pawn_attacks_white_lookup_f4,
    pawn_attacks_white_lookup_g4,
    pawn_attacks_white_lookup_h4,
    pawn_attacks_white_lookup_a3,
    pawn_attacks_white_lookup_b3,
    pawn_attacks_white_lookup_c3,
    pawn_attacks_white_lookup_d3,
    pawn_attacks_white_lookup_e3,
    pawn_attacks_white_lookup_f3,
    pawn_attacks_white_lookup_g3,
    pawn_attacks_white_lookup_h3,
    pawn_attacks_white_lookup_a2,
    pawn_attacks_white_lookup_b2,
    pawn_attacks_white_lookup_c2,
    pawn_attacks_white_lookup_d2,
    pawn_attacks_white_lookup_e2,
    pawn_attacks_white_lookup_f2,
    pawn_attacks_white_lookup_g2,
    pawn_attacks_white_lookup_h2,
    pawn_attacks_white_lookup_a1,
    pawn_attacks_white_lookup_b1,
    pawn_attacks_white_lookup_c1,
    pawn_attacks_white_lookup_d1,
    pawn_attacks_white_lookup_e1,
    pawn_attacks_white_lookup_f1,
    pawn_attacks_white_lookup_g1,
    pawn_attacks_white_lookup_h1
};


// pawn_attacks_black_lookup
const lte *pawn_attacks_black_lookup[] =
{
    pawn_attacks_black_lookup_a8,
    pawn_attacks_black_lookup_b8,
    pawn_attacks_black_lookup_c8,
    pawn_attacks_black_lookup_d8,
    pawn_attacks_black_lookup_e8,
    pawn_attacks_black_lookup_f8,
    pawn_attacks_black_lookup_g8,
    pawn_attacks_black_lookup_h8,
    pawn_attacks_black_lookup_a7,
    pawn_attacks_black_lookup_b7,
    pawn_attacks_black_lookup_c7,
    pawn_attacks_black_lookup_d7,
    pawn_attacks_black_lookup_e7,
    pawn_attacks_black_lookup_f7,
    pawn_attacks_black_lookup_g7,
    pawn_attacks_black_lookup_h7,
    pawn_attacks_black_lookup_a6,
    pawn_attacks_black_lookup_b6,
    pawn_attacks_black_lookup_c6,
    pawn_attacks_black_lookup_d6,
    pawn_attacks_black_lookup_e6,
    pawn_attacks_black_lookup_f6,
    pawn_attacks_black_lookup_g6,
    pawn_attacks_black_lookup_h6,
    pawn_attacks_black_lookup_a5,
    pawn_attacks_black_lookup_b5,
    pawn_attacks_black_lookup_c5,
    pawn_attacks_black_lookup_d5,
    pawn_attacks_black_lookup_e5,
    pawn_attacks_black_lookup_f5,
    pawn_attacks_black_lookup_g5,
    pawn_attacks_black_lookup_h5,
    pawn_attacks_black_lookup_a4,
    pawn_attacks_black_lookup_b4,
    pawn_attacks_black_lookup_c4,
    pawn_attacks_black_lookup_d4,
    pawn_attacks_black_lookup_e4,
    pawn_attacks_black_lookup_f4,
    pawn_attacks_black_lookup_g4,
    pawn_attacks_black_lookup_h4,
    pawn_attacks_black_lookup_a3,
    pawn_attacks_black_lookup_b3,
    pawn_attacks_black_lookup_c3,
    pawn_attacks_black_lookup_d3,
    pawn_attacks_black_lookup_e3,
    pawn_attacks_black_lookup_f3,
    pawn_attacks_black_lookup_g3,
    pawn_attacks_black_lookup_h3,
    pawn_attacks_black_lookup_a2,
    pawn_attacks_black_lookup_b2,
    pawn_attacks_black_lookup_c2,
    pawn_attacks_black_lookup_d2,
    pawn_attacks_black_lookup_e2,
    pawn_attacks_black_lookup_f2,
    pawn_attacks_black_lookup_g2,
    pawn_attacks_black_lookup_h2,
    pawn_attacks_black_lookup_a1,
    pawn_attacks_black_lookup_b1,
    pawn_attacks_black_lookup_c1,
    pawn_attacks_black_lookup_d1,
    pawn_attacks_black_lookup_e1,
    pawn_attacks_black_lookup_f1,
    pawn_attacks_black_lookup_g1,
    pawn_attacks_black_lookup_h1
};


// attacks_white_lookup
const lte *attacks_white_lookup[] =
{
    attacks_white_lookup_a8,
    attacks_white_lookup_b8,
    attacks_white_lookup_c8,
    attacks_white_lookup_d8,
    attacks_white_lookup_e8,
    attacks_white_lookup_f8,
    attacks_white_lookup_g8,
    attacks_white_lookup_h8,
    attacks_white_lookup_a7,
    attacks_white_lookup_b7,
    attacks_white_lookup_c7,
    attacks_white_lookup_d7,
    attacks_white_lookup_e7,
    attacks_white_lookup_f7,
    attacks_white_lookup_g7,
    attacks_white_lookup_h7,
    attacks_white_lookup_a6,
    attacks_white_lookup_b6,
    attacks_white_lookup_c6,
    attacks_white_lookup_d6,
    attacks_white_lookup_e6,
    attacks_white_lookup_f6,
    attacks_white_lookup_g6,
    attacks_white_lookup_h6,
    attacks_white_lookup_a5,
    attacks_white_lookup_b5,
    attacks_white_lookup_c5,
    attacks_white_lookup_d5,
    attacks_white_lookup_e5,
    attacks_white_lookup_f5,
    attacks_white_lookup_g5,
    attacks_white_lookup_h5,
    attacks_white_lookup_a4,
    attacks_white_lookup_b4,
    attacks_white_lookup_c4,
    attacks_white_lookup_d4,
    attacks_white_lookup_e4,
    attacks_white_lookup_f4,
    attacks_white_lookup_g4,
    attacks_white_lookup_h4,
    attacks_white_lookup_a3,
    attacks_white_lookup_b3,
    attacks_white_lookup_c3,
    attacks_white_lookup_d3,
    attacks_white_lookup_e3,
    attacks_white_lookup_f3,
    attacks_white_lookup_g3,
    attacks_white_lookup_h3,
    attacks_white_lookup_a2,
    attacks_white_lookup_b2,
    attacks_white_lookup_c2,
    attacks_white_lookup_d2,
    attacks_white_lookup_e2,
    attacks_white_lookup_f2,
    attacks_white_lookup_g2,
    attacks_white_lookup_h2,
    attacks_white_lookup_a1,
    attacks_white_lookup_b1,
    attacks_white_lookup_c1,
    attacks_white_lookup_d1,
    attacks_white_lookup_e1,
    attacks_white_lookup_f1,
    attacks_white_lookup_g1,
    attacks_white_lookup_h1
};


// attacks_black_lookup
const lte *attacks_black_lookup[] =
{
    attacks_black_lookup_a8,
    attacks_black_lookup_b8,
    attacks_black_lookup_c8,
    attacks_black_lookup_d8,
    attacks_black_lookup_e8,
    attacks_black_lookup_f8,
    attacks_black_lookup_g8,
    attacks_black_lookup_h8,
    attacks_black_lookup_a7,
    attacks_black_lookup_b7,
    attacks_black_lookup_c7,
    attacks_black_lookup_d7,
    attacks_black_lookup_e7,
    attacks_black_lookup_f7,
    attacks_black_lookup_g7,
    attacks_black_lookup_h7,
    attacks_black_lookup_a6,
    attacks_black_lookup_b6,
    attacks_black_lookup_c6,
    attacks_black_lookup_d6,
    attacks_black_lookup_e6,
    attacks_black_lookup_f6,
    attacks_black_lookup_g6,
    attacks_black_lookup_h6,
    attacks_black_lookup_a5,
    attacks_black_lookup_b5,
    attacks_black_lookup_c5,
    attacks_black_lookup_d5,
    attacks_black_lookup_e5,
    attacks_black_lookup_f5,
    attacks_black_lookup_g5,
    attacks_black_lookup_h5,
    attacks_black_lookup_a4,
    attacks_black_lookup_b4,
    attacks_black_lookup_c4,
    attacks_black_lookup_d4,
    attacks_black_lookup_e4,
    attacks_black_lookup_f4,
    attacks_black_lookup_g4,
    attacks_black_lookup_h4,
    attacks_black_lookup_a3,
    attacks_black_lookup_b3,
    attacks_black_lookup_c3,
    attacks_black_lookup_d3,
    attacks_black_lookup_e3,
    attacks_black_lookup_f3,
    attacks_black_lookup_g3,
    attacks_black_lookup_h3,
    attacks_black_lookup_a2,
    attacks_black_lookup_b2,
    attacks_black_lookup_c2,
    attacks_black_lookup_d2,
    attacks_black_lookup_e2,
    attacks_black_lookup_f2,
    attacks_black_lookup_g2,
    attacks_black_lookup_h2,
    attacks_black_lookup_a1,
    attacks_black_lookup_b1,
    attacks_black_lookup_c1,
    attacks_black_lookup_d1,
    attacks_black_lookup_e1,
    attacks_black_lookup_f1,
    attacks_black_lookup_g1,
    attacks_black_lookup_h1
};








}
